# Numpy Arrays

Provides extension to python for multi-dimensional arrays.
It is closer to harware(efficiency)
It is designed for scientific computations (convenience)
Also known as array oriented computing.

In [1]:
import numpy as np
a=np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


Why is it useful :Memory efficient container that provides fast numerical operations

In [2]:
#python lists
L=range(1000)
%timeit [i**2 for i in L]

501 µs ± 44.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
a=np.arange(1000)
%timeit a**2

2.29 µs ± 54.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 1. Creating Arrays

#### 1.1 Manual Construction of arrays

In [4]:
#1-D

a=np.array([0,1,2,3])

a

array([0, 1, 2, 3])

In [5]:
#print dimensions 
a.ndim

1

In [6]:
a.shape

(4,)

In [7]:
#2d,3d
b=np.array([[0,1,2],[3,4,5]])

In [8]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b.ndim #dimension 

2

In [11]:
b.shape # 2 rows and 3 columns

(2, 3)

In [12]:
len(b) #size of first dimension

2

In [14]:
c=np.array( [ [ [ 0 , 1 ] , [ 2 , 3 ]],[[4,5],[6,7]]])

In [15]:
c.ndim

3

In [17]:
c.shape

(2, 2, 2)

1D Array -> vector
2D Array -> matrix
nD Array -> Tensor
(3,4,5)

#### 1.2 Functions for  creating arrays

In [19]:
# using arange function

#arange is an array-valued version of the built-in Python range functions

a=np.arange(10) #0..........n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b=np.arange(1,10,2)  # strat, end and step size
b

array([1, 3, 5, 7, 9])

In [21]:
#using linspace
a=np.linspace(0,1,6) # start,end,number of points

In [22]:
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [23]:
#common arrays
a=np.ones((3,3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
c=np.eye(3) # Return a 2-D array with ones on the diagonal elements 

In [26]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [28]:
#create array using diag functions
a=np.diag([1,2,3,4]) #construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [29]:
np.diag(a) #Extract diagonal

array([1, 2, 3, 4])

In [30]:
#create array using random
#create an array of the given shape and populate it with random samples
a=np.random.rand(4)
a

array([0.73700101, 0.13759401, 0.8014423 , 0.36806565])

In [31]:
a=np.random.randn(4)

In [32]:
a

array([-1.01807909, -0.45532399, -2.14821342, -0.40420705])

## Basic Data Types

In [33]:
a=np.arange(10)

a.dtype

dtype('int32')

In [34]:
#You can explicitly specify which data type you want
a=np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
#The default data type is float for zeros and ones function

a=np.zeros((3,3))

In [36]:
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

##### other datatypes

In [37]:
d=np.array([1+2j,2+4j])
print(d.dtype)

complex128


In [38]:
b=np.array([True,False,True,False])
print(b.dtype)

bool


In [39]:
s=np.array(['Ram','Robert','Rahim'])
s.dtype

dtype('<U6')

##### Each built-in data type has a character code that uniquely identifies it

### Indexing and slicing

In [40]:
a=np.arange(10)

print(a[5])  #indices begin at 0, like other python sequences  (and C/C++)

5


In [41]:
#For multidimensional arrays, indexes are tuples of integers:
a=np.diag([1,2,3])
print(a[2,2])

3


In [42]:
a[2,1]=5 #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

#### slicing

In [43]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a[1:8:2] #startindex:endindex(exclusive):stepsize

array([1, 3, 5, 7])

In [46]:
#we can also combine assignment and slicing:

a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [47]:
b=np.arange(5)
a[5:]=b[::-1] #assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

### 4. Copies and views

In [48]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [50]:
np.shares_memory(a,b )

True